// Generated by tools/gravity/parse_jump_tables.py --csharp-out
// Source: proof/gravity/JumpParam.tab (extracted from settings/JumpParam.tab)
// Do not hand-edit; regenerate after a new table extraction.
//
// JX3 jump chain (verified in docs/movement/JX3_DOUBLE_JUMP_RESEARCH.md):
//   Triples[school][0] = first 跳跃, [1] = 二段跳 press, [2]/[3] = further presses.
//   Each triple is { JumpSpeedXY, VelocityZ, Gravity } in units per 15 Hz
//   logic frame (1 m = 192 u; tick = 1/15 s).
internal static class JumpTable
{
    public static readonly int[] MaxJumpCount = new int[] { 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 4, 4, 11, 11, 11, 8, 8, 15, 14, 15, 13, 13, 6 };

    public static readonly int[][][] Triples = new int[][][]
    {
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 30, 300, 20 }, new int[] { 50, 400, 20 }, new int[] { 100, -250, 8 } }, // school 0
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 40, 180, 12 }, new int[] { 65, 15, 3 }, new int[] { 100, 780, 30 }, new int[] { 100, -250, 30 } }, // school 1
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 60, 450, 30 }, new int[] { 80, 600, 24 }, new int[] { 80, 600, 24 }, new int[] { 100, -250, 8 } }, // school 2
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 50, 400, 25 }, new int[] { 70, 300, 13 }, new int[] { 100, 700, 36 }, new int[] { 100, -250, 8 } }, // school 3
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 50, 160, 8 }, new int[] { 70, 240, 7 }, new int[] { 100, 700, 36 }, new int[] { 100, -250, 8 } }, // school 4
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 40, 160, 6 }, new int[] { 50, 250, 12 }, new int[] { 80, 600, 20 }, new int[] { 100, -250, 8 } }, // school 5
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 65, 36, 4 }, new int[] { 60, 150, 7 }, new int[] { 100, 800, 36 }, new int[] { 120, -70, 10 } }, // school 6
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 65, 36, 4 }, new int[] { 60, 150, 7 }, new int[] { 100, 800, 36 }, new int[] { 120, -70, 10 } }, // school 7
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 40, 400, 10 }, new int[] { 160, 400, 25 }, new int[] { 60, 600, 12 }, new int[] { 160, -500, 14 } }, // school 8
        new int[][] { new int[] { 40, 120, 11 }, new int[] { 25, 1000, 25 }, new int[] { 0, 0, 0 }, new int[] { 75, 600, 16 }, new int[] { 0, 0, 0 }, new int[] { 120, -120, 20 } }, // school 9
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 40, 80, 80 }, new int[] { 40, 80, 60 }, new int[] { 120, -200, 20 } }, // school 10
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 40, 80, 80 }, new int[] { 40, 80, 60 }, new int[] { 120, -200, 20 } }, // school 11
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 50, 400, 25 }, new int[] { 70, 300, 13 }, new int[] { 100, 700, 36 }, new int[] { 100, -250, 8 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 } }, // school 12
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 50, 400, 25 }, new int[] { 70, 300, 13 }, new int[] { 100, 700, 36 }, new int[] { 100, -250, 8 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 } }, // school 13
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 50, 400, 25 }, new int[] { 70, 300, 13 }, new int[] { 100, 700, 36 }, new int[] { 100, -250, 8 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 } }, // school 14
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 50, 400, 25 }, new int[] { 70, 300, 13 }, new int[] { 100, 700, 36 }, new int[] { 100, -250, 8 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 } }, // school 15
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 50, 400, 25 }, new int[] { 70, 300, 13 }, new int[] { 100, 700, 36 }, new int[] { 100, -250, 8 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 } }, // school 16
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 50, 400, 25 }, new int[] { 70, 300, 13 }, new int[] { 100, 700, 36 }, new int[] { 100, -250, 8 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 10, 10, 10 }, new int[] { 10, 10, 10 }, new int[] { 10, 10, 10 }, new int[] { 10, 10, 10 } }, // school 17
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 50, 400, 25 }, new int[] { 70, 300, 13 }, new int[] { 100, 700, 36 }, new int[] { 100, -250, 8 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 10, 10, 10 }, new int[] { 10, 10, 10 }, new int[] { 10, 10, 10 } }, // school 18
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 50, 400, 25 }, new int[] { 70, 300, 13 }, new int[] { 100, 700, 36 }, new int[] { 100, -250, 8 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 10, 10, 10 }, new int[] { 10, 10, 10 }, new int[] { 10, 10, 10 }, new int[] { 10, 10, 10 } }, // school 19
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 50, 400, 25 }, new int[] { 70, 300, 13 }, new int[] { 100, 700, 36 }, new int[] { 100, -250, 8 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 10, 10, 10 }, new int[] { 10, 10, 10 } }, // school 20
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 50, 400, 25 }, new int[] { 70, 300, 13 }, new int[] { 100, 700, 36 }, new int[] { 100, -250, 8 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 120, 10, 10 }, new int[] { 10, 10, 10 }, new int[] { 10, 10, 10 } }, // school 21
        new int[][] { new int[] { 40, 90, 11 }, new int[] { 50, 400, 25 }, new int[] { 70, 300, 13 }, new int[] { 100, 700, 36 }, new int[] { 100, -250, 8 }, new int[] { 120, 10, 10 } }, // school 22
    };
}
