// Generated by tools/character/water_surfaces.py --csharp-out
// Source: data\source\maps\<map>\water\surface\watersurfacelist.json
// (client PakV4 store; provenance samples/water_surfaces/, ignored).
// Do not hand-edit; regenerate after a store update.
//
// WaterType 0 = global ocean plane (covers every cell whose ground is
// below the surface); 1 = bwater body (Position = surface plane, Scale =
// authored scale; footprint heuristic lives in client/WaterField.cs as
// the registered P1 mapping).
internal static class WaterSurfaces
{
    public struct Body
    {
        public int Type;
        public float X, Y, Z, ScaleX, ScaleZ, BaseW, BaseL, Depth, RotY;
    }

    static readonly Body[] None = new Body[0];

    public static Body[] For(string mapName)
    {
        if (mapName == null) return None;
        switch (mapName)
        {
        case "龙门寻宝": return new Body[] { new Body { Type=1, X=139423.453125f, Y=150.0f, Z=31167.1796875f, ScaleX=1.0f, ScaleZ=1.0f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f }, new Body { Type=1, X=67039.8515625f, Y=150.0f, Z=58548.55859375f, ScaleX=2.0f, ScaleZ=2.0f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f }, new Body { Type=1, X=178608.703125f, Y=4738.89990234375f, Z=100072.3984375f, ScaleX=3.000000238418579f, ScaleZ=3.000000238418579f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f }, new Body { Type=1, X=150700.078125f, Y=-457.748046875f, Z=53040.375f, ScaleX=5.0f, ScaleZ=5.0f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f }, new Body { Type=1, X=134207.703125f, Y=-758.7286376953125f, Z=47338.79296875f, ScaleX=3.0f, ScaleZ=4.0f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f }, new Body { Type=1, X=180412.609375f, Y=-463.40283203125f, Z=55823.2890625f, ScaleX=8.0f, ScaleZ=5.0f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f } };
        case "龙门寻宝_夜晚": return new Body[] { new Body { Type=1, X=139423.453125f, Y=150.0f, Z=31167.1796875f, ScaleX=1.0f, ScaleZ=1.0f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f }, new Body { Type=1, X=67039.8515625f, Y=150.0f, Z=58548.55859375f, ScaleX=2.0f, ScaleZ=2.0f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f }, new Body { Type=1, X=178608.703125f, Y=4738.89990234375f, Z=100072.3984375f, ScaleX=3.000000238418579f, ScaleZ=3.000000238418579f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f }, new Body { Type=1, X=150700.078125f, Y=-457.748046875f, Z=53040.375f, ScaleX=5.0f, ScaleZ=5.0f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f }, new Body { Type=1, X=134207.703125f, Y=-758.7286376953125f, Z=47338.79296875f, ScaleX=3.0f, ScaleZ=4.0f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f }, new Body { Type=1, X=180412.609375f, Y=-463.40283203125f, Z=55823.2890625f, ScaleX=8.0f, ScaleZ=5.0f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f } };
        case "海岛绝境": return new Body[] { new Body { Type=0, X=0.0f, Y=0.0f, Z=0.0f, ScaleX=1.0f, ScaleZ=1.0f, BaseW=1000000000.0f, BaseL=1000000000.0f, Depth=1000000.0f }, new Body { Type=1, X=54396.80078125f, Y=-5382.693359375f, Z=99809.3984375f, ScaleX=15.357267379760742f, ScaleZ=15.357267379760742f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f }, new Body { Type=1, X=34452.94921875f, Y=-1505.9586181640625f, Z=114422.484375f, ScaleX=8.731673240661621f, ScaleZ=8.731672286987305f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f }, new Body { Type=1, X=53847.9921875f, Y=402.40704345703125f, Z=50361.89453125f, ScaleX=7.673458099365234f, ScaleZ=7.673458576202393f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f } };
        case "白龙绝境": return new Body[] { new Body { Type=1, X=101064.421875f, Y=10223.626953125f, Z=81327.8359375f, ScaleX=1.0f, ScaleZ=1.0f, BaseW=392.0f, BaseL=306.0f, Depth=1000000.0f }, new Body { Type=1, X=101092.4140625f, Y=7584.8671875f, Z=76507.578125f, ScaleX=1.0f, ScaleZ=1.0f, BaseW=330.0f, BaseL=258.0f, Depth=1000000.0f }, new Body { Type=0, X=176737.796875f, Y=2622.89990234375f, Z=133103.0f, ScaleX=1.0f, ScaleZ=1.0f, BaseW=1000000000.0f, BaseL=1000000000.0f, Depth=1000000.0f }, new Body { Type=1, X=108924.296875f, Y=11938.962890625f, Z=93209.5625f, ScaleX=1.0f, ScaleZ=1.0f, BaseW=162.0f, BaseL=70.0f, Depth=1000000.0f }, new Body { Type=1, X=28021.615234375f, Y=12302.8740234375f, Z=159478.25f, ScaleX=9.0f, ScaleZ=18.0f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f }, new Body { Type=1, X=21345.35546875f, Y=9475.0849609375f, Z=104404.9375f, ScaleX=6.243218898773193f, ScaleZ=6.776386260986328f, BaseW=40.0f, BaseL=40.0f, Depth=1000000.0f }, new Body { Type=1, X=101761.5390625f, Y=6571.908203125f, Z=75622.21875f, ScaleX=1.0f, ScaleZ=1.0f, BaseW=364.0f, BaseL=284.0f, Depth=1000000.0f }, new Body { Type=1, X=103972.7734375f, Y=5343.7861328125f, Z=73948.8671875f, ScaleX=1.0f, ScaleZ=1.0f, BaseW=338.0f, BaseL=296.0f, Depth=1000000.0f }, new Body { Type=1, X=113396.1484375f, Y=4182.763671875f, Z=81270.1796875f, ScaleX=1.0f, ScaleZ=1.0f, BaseW=212.0f, BaseL=136.0f, Depth=1000000.0f }, new Body { Type=1, X=111705.640625f, Y=3213.2373046875f, Z=78695.3125f, ScaleX=1.0f, ScaleZ=1.0f, BaseW=284.0f, BaseL=130.0f, Depth=1000000.0f } };
        case "天原绝境": return new Body[] { new Body { Type=1, X=220944.53125f, Y=-3145.9111328125f, Z=178931.078125f, ScaleX=13.367813110351562f, ScaleZ=9.404892921447754f, BaseW=40.0f, BaseL=40.0f, Depth=10.0f }, new Body { Type=1, X=22595.8046875f, Y=18457.15625f, Z=178118.578125f, ScaleX=9.830799102783203f, ScaleZ=10.779210090637207f, BaseW=40.0f, BaseL=40.0f, Depth=10.0f }, new Body { Type=1, X=448829.3125f, Y=-3534.2177734375f, Z=-107466.640625f, ScaleX=137.9007568359375f, ScaleZ=134.24014282226562f, BaseW=40.0f, BaseL=40.0f, Depth=4000.0f }, new Body { Type=1, X=183641.671875f, Y=-2936.990234375f, Z=152640.34375f, ScaleX=5.458989143371582f, ScaleZ=8.373565673828125f, BaseW=40.0f, BaseL=40.0f, Depth=500.0f }, new Body { Type=1, X=137278.71875f, Y=16556.107421875f, Z=207365.265625f, ScaleX=9.76570987701416f, ScaleZ=13.627769470214844f, BaseW=40.0f, BaseL=40.0f, Depth=500.0f }, new Body { Type=1, X=212461.71875f, Y=-3433.784912109375f, Z=153883.640625f, ScaleX=8.881678581237793f, ScaleZ=13.541460037231445f, BaseW=40.0f, BaseL=40.0f, Depth=500.0f }, new Body { Type=1, X=74774.6875f, Y=6674.05224609375f, Z=101817.140625f, ScaleX=13.360411643981934f, ScaleZ=12.924290657043457f, BaseW=40.0f, BaseL=40.0f, Depth=4000.0f } };
        }
        return None;
    }
}
