// Generated by tools/character/water_region.py -- regenerate after a store/map update.
// Source: data\source\maps\<map>\water\regiondata\RegionInfo.json (region tree, key
// decoded from KG3D_LoaderNoRenderX64.dll 0x1800245b0) + watersurfacelist.json height.
// A region is a 102400-u square (1024 cells, 16x16 leaves of 64 cells) at the world
// origin the ReferNode key encodes; height is the shipped water surface there.
// The engine narrows the shoreline with the region hole/normal masks (not decoded);
// the host uses the block AABB gated on ground < surface.
internal static class WaterRegions
{
    public struct Region
    {
        public float X0, Z0, X1, Z1;
        public float Surface;
        public int SurfaceId;
        public int LeafCount;
    }

    static readonly Region[] None = new Region[0];

    public static Region[] For(string mapName)
    {
        if (mapName == null) return None;
        switch (mapName)
        {
        case "龙门寻宝": return new Region[] { new Region { X0=0.0f, Z0=0.0f, X1=102400.0f, Z1=102400.0f, Surface=150.0f, SurfaceId=0, LeafCount=256 } };
        case "龙门寻宝_夜晚": return new Region[] { new Region { X0=0.0f, Z0=0.0f, X1=102400.0f, Z1=102400.0f, Surface=150.0f, SurfaceId=0, LeafCount=256 } };
        }
        return None;
    }
}
