using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using Reborn.Rules;

namespace Reborn.Rules.Selftest
{
    /// <summary>
    /// Replays proof/netcode/parity/rules_vectors.txt (generated by the Python reference
    /// model) against the C# shared rules. Exit 0 iff every vector matches.
    ///
    /// Usage: Reborn.Rules.Selftest [path-to-rules_vectors.txt]
    /// </summary>
    internal static class Program
    {
        static int pass;
        static int fail;

        static int Main(string[] args)
        {
            string path = args.Length > 0 ? args[0] : "proof/netcode/parity/rules_vectors.txt";
            if (!File.Exists(path))
            {
                Console.WriteLine("vectors not found: " + path);
                return 2;
            }

            double clockMs = 0.0;
            ReliableChannel channel = new ReliableChannel(delegate { return clockMs; });

            foreach (string raw in File.ReadAllLines(path))
            {
                string line = raw.Trim();
                if (line.Length == 0 || line.StartsWith("#")) continue;
                int arrow = line.IndexOf(" -> ", StringComparison.Ordinal);
                string left = arrow >= 0 ? line.Substring(0, arrow) : line;
                string right = arrow >= 0 ? line.Substring(arrow + 4) : "";
                string[] parts = left.Split(' ');
                string kind = parts[0];

                switch (kind)
                {
                    case "input":
                        CheckInput(parts, right);
                        break;
                    case "frame":
                        CheckFrame(parts, right);
                        break;
                    case "chan":
                        CheckChannel(parts, right, ref clockMs, channel);
                        break;
                    case "cast":
                        CheckCast(parts, right);
                        break;
                    case "tick":
                        CheckTick(parts, right);
                        break;
                    case "jump":
                        CheckJump(parts, right);
                        break;
                    case "conv":
                        CheckConv(parts, right);
                        break;
                    default:
                        Fail("unknown vector kind: " + kind);
                        break;
                }
            }

            Console.WriteLine("selftest: {0} PASS, {1} FAIL", pass, fail);
            return fail == 0 ? 0 : 1;
        }

        static void Check(string name, bool ok, string detail)
        {
            if (ok) { pass++; Console.WriteLine("PASS: " + name + (detail.Length > 0 ? " - " + detail : "")); }
            else { fail++; Console.WriteLine("FAIL: " + name + (detail.Length > 0 ? " - " + detail : "")); }
        }

        static void Fail(string name)
        {
            fail++;
            Console.WriteLine("FAIL: " + name);
        }

        static double D(string s)
        {
            return double.Parse(s, NumberStyles.Float, CultureInfo.InvariantCulture);
        }

        static string F(double v)
        {
            return v.ToString("G17", CultureInfo.InvariantCulture);
        }

        static bool Near(double a, double b)
        {
            return Math.Abs(a - b) <= 1e-9;
        }

        static void CheckInput(string[] parts, string right)
        {
            double[] pos = new double[] { D(parts[1]), D(parts[2]), D(parts[3]) };
            int keys = int.Parse(parts[4], CultureInfo.InvariantCulture);
            double dt = D(parts[5]);
            double speed = D(parts[6]);
            double[] want = Parse3(right);
            double[] got = Movement.ApplyInput(pos, keys, dt, speed);
            Check("input keys=" + keys, Near(got[0], want[0]) && Near(got[1], want[1]) && Near(got[2], want[2]),
                "got=(" + F(got[0]) + "," + F(got[1]) + "," + F(got[2]) + ")");
        }

        static void CheckFrame(string[] parts, string right)
        {
            ushort op = ushort.Parse(parts[1], CultureInfo.InvariantCulture);
            byte flags = byte.Parse(parts[2], CultureInfo.InvariantCulture);
            int seq = int.Parse(parts[3], CultureInfo.InvariantCulture);
            int ack = int.Parse(parts[4], CultureInfo.InvariantCulture);
            uint sid = uint.Parse(parts[5], CultureInfo.InvariantCulture);
            uint param = uint.Parse(parts[6], CultureInfo.InvariantCulture);
            byte[] payload = parts[7] == "-" ? new byte[0] : Hex(parts[7]);
            byte[] got = Protocol.Encode(op, seq, ack, param, payload, flags, sid);
            Check("frame op=" + op, HexStr(got) == right, "got=" + HexStr(got));
            Protocol.Frame back = Protocol.Decode(got);
            Check("frame roundtrip op=" + op,
                back.Op == op && back.Flags == flags && back.Seq == (ushort)seq && back.Ack == (ushort)ack &&
                back.Sid == sid && back.Param == param && HexStr(back.Payload) == (parts[7] == "-" ? "" : parts[7]),
                "");
        }

        static void CheckChannel(string[] parts, string right, ref double clockMs, ReliableChannel ch)
        {
            switch (parts[1])
            {
                case "clock":
                    clockMs = D(parts[2]) * 1000.0;
                    return;
                case "build":
                {
                    ushort op = ushort.Parse(parts[2], CultureInfo.InvariantCulture);
                    uint param = uint.Parse(parts[3], CultureInfo.InvariantCulture);
                    byte[] payload = parts[4] == "-" ? new byte[0] : Hex(parts[4]);
                    byte[] frame = ch.Build(op, param, payload, 0);
                    Check("chan build op=" + op, frame != null && HexStr(frame) == right,
                        "got=" + (frame == null ? "<null>" : HexStr(frame)));
                    return;
                }
                case "due":
                {
                    clockMs = D(parts[2]) * 1000.0;
                    List<byte[]> due = ch.Due();
                    string got = due.Count == 0 ? "-" : string.Join(" ", due.ConvertAll(HexStr).ToArray());
                    Check("chan due t=" + parts[2], got == right, "got=" + got);
                    return;
                }
                case "onframe":
                {
                    bool ok = ch.OnFrame(int.Parse(parts[2], CultureInfo.InvariantCulture),
                                         int.Parse(parts[3], CultureInfo.InvariantCulture));
                    Check("chan onframe seq=" + parts[2] + " ack=" + parts[3], (ok ? "1" : "0") == right, "");
                    return;
                }
                case "state":
                {
                    string got = string.Format(CultureInfo.InvariantCulture,
                        "sendseq={0} recvack={1} unacked={2} retransmits={3}",
                        ch.SendSeq, ch.RecvAck, ch.UnackedCount, ch.Retransmits);
                    Check("chan state", got == right, "got=" + got);
                    return;
                }
                default:
                    Fail("unknown chan op: " + parts[1]);
                    return;
            }
        }

        static void CheckCast(string[] parts, string right)
        {
            int skill = int.Parse(parts[1], CultureInfo.InvariantCulture);
            bool moving = parts[2] == "1";
            double nowS = D(parts[3]);
            double ready = D(parts[4]);
            bool hasTarget = parts[5] == "1";
            double dist = D(parts[6]);
            int code = Combat.ValidateCast(skill, moving, nowS, ready, hasTarget, dist);
            Check("cast skill=" + skill + " moving=" + moving, code.ToString(CultureInfo.InvariantCulture) == right,
                "got=" + code);
        }

        static void CheckJump(string[] parts, string right)
        {
            int vz0 = int.Parse(parts[1], CultureInfo.InvariantCulture);
            int g = int.Parse(parts[2], CultureInfo.InvariantCulture);
            GameMovement.JumpResult r = GameMovement.SimulateJump(vz0, g, 2000);
            string[] want = right.Split(' ');
            Check("jump vz0=" + vz0 + " g=" + g,
                Near(r.ApexUnits, D(want[0])) && r.ApexFrame == int.Parse(want[1], CultureInfo.InvariantCulture) &&
                r.AirFrames == int.Parse(want[2], CultureInfo.InvariantCulture),
                "got=(" + F(r.ApexUnits) + "," + r.ApexFrame + "," + r.AirFrames + ")");
        }

        static void CheckConv(string[] parts, string right)
        {
            double want = D(right);
            double got;
            if (parts[1] == "v") got = GameMovement.UnitsPerFrameToMetersPerSecond(D(parts[2]));
            else got = GameMovement.UnitsPerFrame2ToMetersPerSecond2(D(parts[2]));
            Check("conv " + parts[1] + " " + parts[2], Near(got, want), "got=" + F(got));
        }

        static void CheckTick(string[] parts, string right)
        {
            int keys = int.Parse(parts[1], CultureInfo.InvariantCulture);
            int ticks = int.Parse(parts[2], CultureInfo.InvariantCulture);
            double dt = D(parts[3]);
            double speed = D(parts[4]);
            GameState state = new GameState();
            state.MoveSpeed = speed;
            Entity ent = state.Spawn("t");
            ent.Keys = keys;
            for (int i = 0; i < ticks; i++) state.Step(0.0, dt);
            double[] want = Parse3(right);
            Check("tick keys=" + keys + " ticks=" + ticks,
                Near(ent.Pos[0], want[0]) && Near(ent.Pos[1], want[1]) && Near(ent.Pos[2], want[2]),
                "got=(" + F(ent.Pos[0]) + "," + F(ent.Pos[1]) + "," + F(ent.Pos[2]) + ")");
        }

        static double[] Parse3(string s)
        {
            string[] p = s.Split(' ');
            return new double[] { D(p[0]), D(p[1]), D(p[2]) };
        }

        static byte[] Hex(string s)
        {
            byte[] b = new byte[s.Length / 2];
            for (int i = 0; i < b.Length; i++)
                b[i] = byte.Parse(s.Substring(i * 2, 2), NumberStyles.HexNumber, CultureInfo.InvariantCulture);
            return b;
        }

        static string HexStr(byte[] b)
        {
            char[] c = new char[b.Length * 2];
            const string hex = "0123456789abcdef";
            for (int i = 0; i < b.Length; i++)
            {
                c[i * 2] = hex[b[i] >> 4];
                c[i * 2 + 1] = hex[b[i] & 0xF];
            }
            return new string(c);
        }
    }
}
