#!/usr/bin/env python3
"""Decode a map's water region tree into host world-space water regions.

Source of truth (shipped/editor map data):
  data\\source\\maps\\<map>\\water\\regiondata\\RegionInfo.json
The loader is KG3D_LoaderNoRenderX64.dll fn 0x1800245b0 (release 1-5-0). It reads
the JSON and, for every terrain region in the map's region table, computes a
``ReferNode`` key from the region's world origin:

    Vx = trunc(minWorldX / (RegionSize * UnitScale))     ; RegionSize=512 cells, UnitScale=100 u
    Vy = trunc(minWorldZ / (RegionSize * UnitScale))
    key = "%d%03d_%d%03d" % (Vx >= 0, abs(Vx), Vy >= 0, abs(Vy))    ; 0x180024854

(descriptor built by ``_InitializeAreaRegions`` 0x18002f300: desc+0xc =
 minWorldX = N*col*UnitScale + WorldOriginX, desc+8 = N = RegionSize). So a key
field is a sign digit ('1' = non-negative, '0' = negative) followed by the
3-digit magnitude of the region's world origin in units of 51200 u.

Each matched ReferNode carries a BlockData array; every entry has a LeafNodeIndex
and a WUnique_<n> with a WaterSurfaceID. The leaf grid is 16x16 over the region:
    bx = LeafNodeIndex & 0xF, by = LeafNodeIndex >> 4        (256 leaves)
A water region spans **1024 cells = 102400 u** (16 leaves x LeafNodeSize 64 cells
x UnitScale 100 u), i.e. 2x2 terrain regions - confirmed by the shipped
``landscapeinfo`` (RegionSize 512, LeafNodeSize 64) and by the map water bodies
falling inside the decoded AABB (龙门寻宝 body 2 at 67039,58548 in region 0,0).

Height: the region's WaterSurfaceID selects the water surface; the shipped
``watersurfacelist.json`` positions are the render bodies, and the body whose XZ
lies inside the region AABB supplies the surface height (fallback: the body with
WaterID == the region's surface id).

Usage:
    .venv\\Scripts\\python.exe tools\\character\\water_region.py \
        --region-info C:\\jx3tmp\\...\\RegionInfo.json \
        --surface samples\\water_region\\<map>_watersurfacelist.json \
        --map 龙门寻宝 --out client\\WaterRegions.cs --dump
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# 1 terrain region = 512 cells; water region = 2x2 terrain regions = 1024 cells.
TERRAIN_REGION_CELLS = 512
WATER_LEAVES_PER_AXIS = 16


def decode_key(key: str):
    """Return (vx, vy) region coordinates from a ReferNode key.

    Field format: sign digit + 3 magnitude digits, e.g. '1000' -> +0,
    '0002' -> -2, '1005' -> +5.
    """
    a, b = key.split("_", 1)
    return _decode_field(a), _decode_field(b)


def _decode_field(field: str):
    if len(field) != 4:
        raise ValueError("unexpected key field %r" % field)
    pos = field[0] == "1"
    mag = int(field[1:])
    return mag if pos else -mag


def parse_region_info(path: Path, unit: float, leaf_cells: int):
    d = json.loads(path.read_text(encoding="utf-8"))
    step = TERRAIN_REGION_CELLS * unit          # 51200 u per key unit
    extent = WATER_LEAVES_PER_AXIS * leaf_cells * unit
    regions = []
    for key, node in d.get("ReferNode", {}).items():
        vx, vy = decode_key(key)
        x0, z0 = vx * step, vy * step
        leaf_ids = set()
        surface_ids = []
        for blk in node.get("BlockData", []):
            ln = blk.get("LeafNodeIndex")
            if isinstance(ln, int):
                leaf_ids.add(ln)
            for f in blk:
                if f.startswith("WUnique_") and isinstance(blk[f], dict):
                    sid = blk[f].get("WaterSurfaceID")
                    if isinstance(sid, int):
                        surface_ids.append(sid)
        regions.append({
            "key": key, "vx": vx, "vy": vy,
            "x0": x0, "z0": z0, "x1": x0 + extent, "z1": z0 + extent,
            "extent": extent, "leaf_count": len(leaf_ids),
            "surface_id": min(surface_ids) if surface_ids else 0,
        })
    return regions


def load_surface(path: Path):
    if not path or not path.is_file():
        return []
    d = json.loads(path.read_text(encoding="utf-8"))
    bodies = []
    for k, v in d.items():
        if not isinstance(v, dict):
            continue
        pos = v.get("Postion") or [0.0, 0.0, 0.0]
        bodies.append({"id": int(v.get("WaterID", 0)), "x": float(pos[0]),
                       "y": float(pos[1]), "z": float(pos[2])})
    return bodies


def resolve_height(region, bodies):
    # prefer a body inside the region AABB (the actual lake there)
    for b in bodies:
        if region["x0"] <= b["x"] <= region["x1"] and region["z0"] <= b["z"] <= region["z1"]:
            return b["y"]
    for b in bodies:
        if b["id"] == region["surface_id"]:
            return b["y"]
    return 0.0


def csharp(regions_by_map):
    lines = [
        "// Generated by tools/character/water_region.py -- regenerate after a store/map update.",
        "// Source: data\\source\\maps\\<map>\\water\\regiondata\\RegionInfo.json (region tree, key",
        "// decoded from KG3D_LoaderNoRenderX64.dll 0x1800245b0) + watersurfacelist.json height.",
        "// A region is a 102400-u square (1024 cells, 16x16 leaves of 64 cells) at the world",
        "// origin the ReferNode key encodes; height is the shipped water surface there.",
        "// The engine narrows the shoreline with the region hole/normal masks (not decoded);",
        "// the host uses the block AABB gated on ground < surface.",
        "internal static class WaterRegions",
        "{",
        "    public struct Region",
        "    {",
        "        public float X0, Z0, X1, Z1;",
        "        public float Surface;",
        "        public int SurfaceId;",
        "        public int LeafCount;",
        "    }",
        "",
        "    static readonly Region[] None = new Region[0];",
        "",
        "    public static Region[] For(string mapName)",
        "    {",
        "        if (mapName == null) return None;",
        "        switch (mapName)",
        "        {",
    ]
    for name, regions in regions_by_map.items():
        entries = []
        for r in regions:
            entries.append(
                "new Region {{ X0={0}f, Z0={1}f, X1={2}f, Z1={3}f, Surface={4}f, SurfaceId={5}, LeafCount={6} }}".format(
                    r["x0"], r["z0"], r["x1"], r["z1"], r["surface"], r["surface_id"], r["leaf_count"]
                )
            )
        lines.append('        case "{0}": return new Region[] {{ {1} }};'.format(name, ", ".join(entries)))
    lines += [
        "        }",
        "        return None;",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def selftest():
    checks = []
    checks.append(("key +0 -> (0,0)", decode_key("1000_1000") == (0, 0)))
    checks.append(("key -2,+5", decode_key("0002_1005") == (-2, 5)))
    checks.append(("field parse +12", _decode_field("1012") == 12))
    checks.append(("field parse -7", _decode_field("0007") == -7))
    node = {"GSInfo": 0, "BlockData": [
        {"LeafNodeIndex": i, "WUnique_0": {"WaterSurfaceID": 0}} for i in range(256)]}
    # parse a synthetic ReferNode tree via the real parser (needs a file path)
    import tempfile
    with tempfile.TemporaryDirectory() as td:
        p = Path(td) / "RegionInfo.json"
        p.write_text(json.dumps({"ReferNode": {"1000_1000": node}}), encoding="utf-8")
        rs = parse_region_info(p, 100.0, 64)
    r = rs[0]
    checks.append(("origin (0,0)", (r["x0"], r["z0"]) == (0.0, 0.0)))
    checks.append(("extent 102400", r["extent"] == 102400.0))
    checks.append(("256 leaves", r["leaf_count"] == 256))
    # height resolution: a body inside the AABB wins
    bodies = [{"id": 0, "x": 139423.0, "y": 150.0, "z": 31167.0},
              {"id": 2, "x": 67039.0, "y": 150.0, "z": 58548.0}]
    checks.append(("height from in-AABB body", resolve_height(r, bodies) == 150.0))
    ok = all(v for _, v in checks)
    for name, v in checks:
        print("%s  %s" % ("PASS" if v else "FAIL", name))
    print("water_region selftest: %d/%d %s" % (sum(1 for _, v in checks if v), len(checks), "PASS" if ok else "FAIL"))
    return 0 if ok else 1


def main(argv=None):
    if argv is None:
        argv = sys.argv[1:]
    if len(argv) == 1 and argv[0] == "selftest":
        return selftest()
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--region-info", type=Path, required=True)
    ap.add_argument("--surface", type=Path, default=None)
    ap.add_argument("--map", dest="map_name", default="龙门寻宝")
    ap.add_argument("--alias", action="append", default=[],
                    help="extra map name sharing this region data (e.g. night variant)")
    ap.add_argument("--unit", type=float, default=100.0)
    ap.add_argument("--leaf-cells", type=int, default=64)
    ap.add_argument("--out", type=Path, default=None)
    ap.add_argument("--dump", action="store_true")
    args = ap.parse_args(argv)

    regions = parse_region_info(args.region_info, args.unit, args.leaf_cells)
    bodies = load_surface(args.surface)
    for r in regions:
        r["surface"] = resolve_height(r, bodies)

    if args.dump or not args.out:
        print("region-info:", args.region_info)
        print("surface bodies:", len(bodies))
        for r in regions:
            print("  key=%-9s v=(%d,%d) origin=(%.0f,%.0f) extent=%.0f leaves=%d surface_id=%d height=%.1f"
                  % (r["key"], r["vx"], r["vy"], r["x0"], r["z0"], r["extent"],
                     r["leaf_count"], r["surface_id"], r["surface"]))
    if args.out:
        by_map = {args.map_name: regions}
        for a in args.alias:
            by_map[a] = regions
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(csharp(by_map), encoding="utf-8", newline="\n")
        print("wrote", args.out, "(%d regions)" % len(regions))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
