"""Water surfaces per map -- extract + generate the client C# table.

Source of truth: ``data\\source\\maps\\<map>\\water\\surface\\watersurfacelist.json``
in the client PakV4 store (SPEC_STATES.md section 1.1). This tool extracts the
five shipped maps' lists with the official PakV4SfxExtract.exe into an ignored
dir (provenance) and emits ``client/WaterSurfaces.cs`` for the host.

The list carries the authored surface planes (Position.y = water surface,
WaterType 0 = global ocean plane, 1 = bwater body with Position/Scale). The
footprint of a bwater body is NOT in the data (the .jsonins files are materials);
the host maps it with a registered heuristic (SPEC_STATES.md P1) -- see
``client/WaterField.cs``.

Usage:
    .venv\\Scripts\\python.exe tools\\character\\water_surfaces.py \
        --out-dir samples\\water_surfaces --csharp-out client\\WaterSurfaces.cs
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
EXTRACTOR = Path(
    r"C:\SeasunGame\Game\JX3\bin\zhcn_hd\bin64\PakV4SfxExtract.exe"
)
MAPS = [
    "龙门寻宝",
    "龙门寻宝_夜晚",
    "海岛绝境",
    "白龙绝境",
    "天原绝境",
]


def _write_pathlist(path: Path, entries: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = "\r\n".join(entries) + "\r\n"
    path.write_bytes(text.encode("gb18030", errors="replace"))


def run_pakv4(entries: list[str], work: Path) -> dict[str, bytes]:
    """Run the official extractor for ``entries``; return logical path -> bytes.

    Ported from tools/sandbox/build_sandbox.py (the frozen root pss_assets
    module must not be imported by new tools).
    """
    if not EXTRACTOR.is_file():
        raise FileNotFoundError("PakV4SfxExtract not found: %s" % EXTRACTOR)
    if not entries:
        return {}
    # Absolute paths only: the extractor runs with its own cwd, so relative
    # paths would be created under the game install (read-only, AGENTS §8).
    list_path = (work / "pathlist.txt").resolve()
    out_dir = (work / "out").resolve()
    if str(out_dir).lower().startswith(r"c:\seasungame"):
        raise ValueError("refusing to write under C:\\SeasunGame: %s" % out_dir)
    _write_pathlist(list_path, entries)
    if out_dir.exists():
        shutil.rmtree(out_dir, ignore_errors=True)
    out_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [str(EXTRACTOR), str(list_path), str(out_dir)],
        cwd=str(EXTRACTOR.parent),
        capture_output=True,
        text=True,
        timeout=900,
    )
    found: dict[str, bytes] = {}
    for file in out_dir.rglob("*"):
        if file.is_file() and not file.name.startswith("_"):
            rel = file.relative_to(out_dir).as_posix()
            found[rel] = file.read_bytes()
    return found


def parse_list(raw: bytes) -> list[dict]:
    d = json.loads(raw.decode("utf-8", errors="replace"))
    bodies = []
    for key, value in d.items():
        if not isinstance(value, dict):
            continue
        pos = value.get("Postion") or [0.0, 0.0, 0.0]
        scale = value.get("Scale") or [1.0, 1.0]
        bodies.append(
            {
                "id": int(value.get("WaterID", 0)),
                "type": int(value.get("WaterType", 1)),
                "x": float(pos[0]),
                "y": float(pos[1]),
                "z": float(pos[2]),
                "sx": float(scale[0]),
                "sz": float(scale[1]),
                "bw": float(value.get("BaseWidth", 0.0)),
                "bl": float(value.get("BaseLenght", 0.0)),
                "depth": float(value.get("Depth", 0.0)),
            }
        )
    bodies.sort(key=lambda b: b["id"])
    return bodies


def csharp_table(maps: dict[str, list[dict]]) -> str:
    lines = [
        "// Generated by tools/character/water_surfaces.py --csharp-out",
        "// Source: data\\source\\maps\\<map>\\water\\surface\\watersurfacelist.json",
        "// (client PakV4 store; provenance samples/water_surfaces/, ignored).",
        "// Do not hand-edit; regenerate after a store update.",
        "//",
        "// WaterType 0 = global ocean plane (covers every cell whose ground is",
        "// below the surface); 1 = bwater body (Position = surface plane, Scale =",
        "// authored scale; footprint heuristic lives in client/WaterField.cs as",
        "// the registered P1 mapping).",
        "internal static class WaterSurfaces",
        "{",
        "    public struct Body",
        "    {",
        "        public int Type;",
        "        public float X, Y, Z, ScaleX, ScaleZ, BaseW, BaseL, Depth;",
        "    }",
        "",
    ]
    arr_lines = []
    for name, bodies in maps.items():
        entries = []
        for b in bodies:
            entries.append(
                "new Body {{ Type={0}, X={1}f, Y={2}f, Z={3}f, ScaleX={4}f, ScaleZ={5}f, BaseW={6}f, BaseL={7}f, Depth={8}f }}".format(
                    b["type"], b["x"], b["y"], b["z"], b["sx"], b["sz"], b["bw"], b["bl"], b["depth"]
                )
            )
        arr_lines.append(
            "        case \"{0}\": return new Body[] {{ {1} }};".format(name, ", ".join(entries))
        )
    lines.append("    static readonly Body[] None = new Body[0];")
    lines.append("")
    lines.append("    public static Body[] For(string mapName)")
    lines.append("    {")
    lines.append("        if (mapName == null) return None;")
    lines.append("        switch (mapName)")
    lines.append("        {")
    lines.extend(arr_lines)
    lines.append("        }")
    lines.append("        return None;")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-dir", type=Path, default=REPO / "samples" / "water_surfaces")
    ap.add_argument("--work", type=Path, default=None)
    ap.add_argument("--csharp-out", type=Path, default=None)
    args = ap.parse_args(argv)

    work = args.work or (args.out_dir / "_work")
    entries = [
        "data\\source\\maps\\%s\\water\\surface\\watersurfacelist.json" % m for m in MAPS
    ]
    found = run_pakv4(entries, work)
    maps: dict[str, list[dict]] = {}
    for m in MAPS:
        key = "data/source/maps/%s/water/surface/watersurfacelist.json" % m
        raw = found.get(key)
        if raw is None:
            print("MISS %s" % m, file=sys.stderr)
            continue
        bodies = parse_list(raw)
        maps[m] = bodies
        dest = args.out_dir / ("%s_watersurfacelist.json" % m)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(raw)
        print("HIT %s: %d bodies -> %s" % (m, len(bodies), dest))
    if args.csharp_out:
        args.csharp_out.parent.mkdir(parents=True, exist_ok=True)
        args.csharp_out.write_text(csharp_table(maps), encoding="utf-8", newline="\n")
        print("wrote %s" % args.csharp_out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
