#!/usr/bin/env python3
"""Generate parity vectors for the C# shared rules (netcode/Reborn.Rules).

The vectors are produced by the Python reference model itself
(tools/netcode/reference/jx3_model.py, 10x PASS) so the C# port is pinned to the
same contract: framing bytes, reliable-channel behaviour under a fake clock,
movement, cast validation and the authoritative tick.

Output: proof/netcode/parity/rules_vectors.txt (committed proof; regenerate any time).

Run:  .venv\\Scripts\\python.exe tools\\netcode\\reference\\gen_parity_vectors.py
"""
from __future__ import annotations

import json
import math
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import jx3_model as M  # noqa: E402

OUT = Path(__file__).resolve().parents[3] / "proof" / "netcode" / "parity" / "rules_vectors.txt"

G = "%.17g"


def fmt3(v):
    return " ".join(G % x for x in v)


def emit(lines, kind, payload, result):
    lines.append("%s %s -> %s" % (kind, payload, result))


def main() -> int:
    lines = []
    lines.append("# parity vectors for netcode/Reborn.Rules (generated by gen_parity_vectors.py)")
    lines.append("# format: <kind> <args> -> <expected>; floats are 17-significant-digit doubles")

    # ---- movement: apply_input ----
    inputs = [
        ((0.0, 0.0, 0.0), M.K_FWD, 1.0 / 30.0),
        ((0.0, 0.0, 0.0), M.K_BACK, 1.0 / 30.0),
        ((0.0, 0.0, 0.0), M.K_LEFT, 1.0 / 30.0),
        ((0.0, 0.0, 0.0), M.K_RIGHT, 1.0 / 30.0),
        ((0.0, 0.0, 0.0), M.K_FWD | M.K_RIGHT, 1.0 / 30.0),
        ((0.0, 0.0, 0.0), M.K_FWD | M.K_LEFT, 0.05),
        ((0.0, 0.0, 0.0), M.K_BACK | M.K_RIGHT, 0.05),
        ((0.0, 0.0, 0.0), M.K_BACK | M.K_LEFT, 1.0 / 30.0),
        ((0.0, 0.0, 0.0), 0, 1.0 / 30.0),
        ((1.5, -2.0, 3.25), M.K_FWD, 1.0 / 30.0),
        ((1.5, -2.0, 3.25), M.K_RIGHT | M.K_BACK, 0.1),
        ((-7.25, 10.5, 0.125), M.K_LEFT, 0.25),
    ]
    for pos, keys, dt in inputs:
        res = M.apply_input(pos, keys, dt)
        emit(lines, "input", "%s %d %s %s" % (fmt3(pos), keys, G % dt, G % M.MOVE_SPEED), fmt3(res))

    # ---- framing: encode/decode ----
    frames = [
        (M.OP_PING, 0, 0x1234, 0xBEEF, b"", 0, 0xDEADBEEF),
        (M.OP_CAST_SKILL, M.FLAG_HAS_ACK, 7, 3, b'{"skill_id":2,"target":0}', 0, 0),
        (M.OP_MOVE_INPUT, M.FLAG_HAS_ACK | M.FLAG_RETRANSMIT, 0xFFFF, 0xFFFE, b'{"keys":9,"facing":0}', 0xFFFFFFFF, 0x01020304),
        (M.OP_HANDSHAKE, M.FLAG_HAS_ACK, 1, 0, bytes(range(19)), 0, 0),
    ]
    for op, flags, seq, ack, payload, sid, param in frames:
        frame = M.encode(op, seq, ack, param, payload, flags, sid)
        emit(lines, "frame", "%d %d %d %d %d %d %s" % (op, flags, seq, ack, sid, param,
                                                        payload.hex() if payload else "-"), frame.hex())
        # round-trip check through the reference decoder
        d = M.decode(frame)
        assert d == (op, flags, seq, ack, sid, param, payload), "reference decode mismatch"

    # ---- reliable channel under a fake clock (seconds) ----
    fake = {"t": 0.0}
    M.now = lambda: fake["t"]  # type: ignore[assignment]
    ch = M.ReliableChannel()
    lines.append("chan clock 0")
    f0 = ch.build(M.OP_PING, 111)
    f1 = ch.build(M.OP_CAST_SKILL, 222, b"aa")
    emit(lines, "chan build", "%d 111 -" % M.OP_PING, f0.hex())
    emit(lines, "chan build", "%d 222 6161" % M.OP_CAST_SKILL, f1.hex())
    fake["t"] = 0.1
    emit(lines, "chan due", "0.1", "-")
    fake["t"] = 0.3
    due = ch.due()
    emit(lines, "chan due", "0.3", " ".join(f.hex() for f in due))
    ok1 = ch.on_frame(7, 0)
    emit(lines, "chan onframe", "7 0", "1" if ok1 else "0")
    fake["t"] = 0.6
    due = ch.due()
    emit(lines, "chan due", "0.6", " ".join(f.hex() for f in due))
    ok2 = ch.on_frame(8, 1)
    emit(lines, "chan onframe", "8 1", "1" if ok2 else "0")
    ok3 = ch.on_frame(8, 1)
    emit(lines, "chan onframe", "8 1", "1" if ok3 else "0")
    fake["t"] = 0.9
    due = ch.due()
    emit(lines, "chan due", "0.9", " ".join(f.hex() for f in due) if due else "-")
    emit(lines, "chan state", "-", "sendseq=%d recvack=%d unacked=%d retransmits=%d" % (
        ch.send_seq, ch.recv_ack, len(ch.unacked), ch.retransmits))

    # ---- cast validation ----
    casts = [
        (1, True, 10.0, 0.0, False, 0.0),
        (1, False, 10.0, 0.0, False, 0.0),
        (1, False, 10.0, 11.0, False, 0.0),
        (2, True, 10.0, 0.0, False, 0.0),
        (2, False, 10.0, 0.0, True, 5.999),
        (2, False, 10.0, 0.0, True, 6.001),
        (1, False, 10.0, 0.0, True, 6.001),
        (99, False, 10.0, 0.0, False, 0.0),
    ]
    for skill, moving, now_s, ready, has_target, dist in casts:
        code = M.REJECT_RANGE
        spec = M.SKILLS.get(skill)
        if spec is None:
            code = M.REJECT_RANGE
        elif spec["move_forbidden"] and moving:
            code = M.REJECT_MOVE_STATE
        elif now_s < ready:
            code = M.REJECT_COOLDOWN
        elif has_target and dist > spec["range"]:
            code = M.REJECT_RANGE
        else:
            code = 0
        emit(lines, "cast", "%d %d %s %s %d %s" % (skill, 1 if moving else 0, G % now_s, G % ready,
                                                   1 if has_target else 0, G % dist), str(code))

    # ---- authoritative tick (one entity, no locks) ----
    for keys, ticks, dt in ((M.K_FWD, 10, 1.0 / 30.0), (M.K_FWD | M.K_RIGHT, 30, 1.0 / 30.0), (0, 5, 1.0 / 30.0)):
        pos = (0.0, 0.0, 0.0)
        for _ in range(ticks):
            pos = M.apply_input(pos, keys, dt)
            if pos[1] < 0.0:
                pos = (pos[0], 0.0, pos[2])
        emit(lines, "tick", "%d %d %s %s" % (keys, ticks, G % dt, G % M.MOVE_SPEED), fmt3(pos))

    # ---- exact integer jump model (docs/movement/REBORN_JUMP_FALL_SPEC.md §3) ----
    sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "gravity"))
    from verify_model import simulate_jump  # noqa: E402
    for vz0, g in ((90, 11), (100, 12), (90, 9), (127, 31), (60, 5)):
        r = simulate_jump(vz0, g)
        emit(lines, "jump", "%d %d" % (vz0, g), "%s %d %d" % (G % r["apex_units"], r["apex_frame"], r["air_frames"]))
    from verify_model import uf_to_ms, uf2_to_ms2  # noqa: E402
    for v in (90, 100, 127):
        emit(lines, "conv", "v %d" % v, G % uf_to_ms(v))
    for g in (11, 31):
        emit(lines, "conv", "g %d" % g, G % uf2_to_ms2(g))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote %s (%d lines)" % (OUT, len(lines)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
